#pragma once

#include <ntdef.h>

#include "lxssex.Service.Shared.h"

DEFINE_ENUM_FLAG_OPERATORS(CHANNEL_EVENT_TYPE)

typedef struct _CHANNEL_REGISTRATION_WINDOWS : CHANNEL_REGISTRATION
{
	HANDLE ChannelEvent;
	PVOID SharedSection;
} CHANNEL_REGISTRATION_WINDOWS, * PCHANNEL_REGISTRATION_WINDOWS;

#define IOCTL_OPEN_CHANNEL CTL_CODE(FILE_DEVICE_UNKNOWN, OpenChannel, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SET_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN, SetEvent, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_GET_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN, GetEvent, METHOD_NEITHER, FILE_ANY_ACCESS)