#pragma once

#include "lxssex.WindowManager.Shared.h"

#define IOCTL_OPEN_CHANNEL_PAIR CTL_CODE(FILE_DEVICE_UNKNOWN, LXSSEX_WM_IOCTL::WMOpenChannelPair, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_QUERY_UNHANDLED_PAIRS CTL_CODE(FILE_DEVICE_UNKNOWN, LXSSEX_WM_IOCTL::WMQueryUnhandledPairs, METHOD_NEITHER, FILE_ANY_ACCESS)